apiVersion: apps/v1
kind: Deployment
metadata:
  name:  my-app
  labels:
    app:  my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: dattranabs/my-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://admin:password@mongodb-service:27017/"
